### PR TITLE
no html returned when using xpath extraction

### PR DESCRIPTION
**Pull request by Seb147**

### CODE REVIEW

**Comment by Seb147** [comment]
I don't really know how to to this, it's my first pull request :)

anyway, here is the scenario that didn't work for me : 

Config : 
    "lesjoiesducode.fr": {
        "type": "xpath",
        "xpath": "p[@class ='e']//img",
        "modify": [
            {
                "type": "replace",
                "search": "jpg",
                "replace": "gif"
            }
        ]

Test url : http://lesjoiesducode.fr/post/108533779672

**Comment by m42e** [comment]
Hi,

 The Problem is, you are referencing an img. There is no inner html. You can add /.. To the end of your xpath and try it once again.

**Comment by Seb147** [comment]
What i want is the image, not html content. But with the plugins, I don't get anything. If I add .//, I will not get the image

**Comment by m42e** [comment]
This works perfect for me:

    "lesjoiesducode.fr": {
        "type": "xpath",
        "xpath": "p[@class ='e']//img/..",
        "modify": [
            {
                "type": "replace",
                "search": "jpg",
                "replace": "gif"
            }
        ]
    }

**Comment by m42e** [comment]
I added a recipe for your request.

**Pull request closed without merging**
